### ISSUE TITLE
Event 詳細ページ

### ISSUE THREAD

**Issue by s-osa** [sdevtalks/sdevtalks.org#42]
## 今後の開発優先順位

Figma に上がってるデザイン良いんだけど、登壇者の画像とかスライドの画像とかを扱うのがちょっと大変なので、先にテキストベースの情報だけでも入れていったほうが見る人のハピネスが高速に高まるのではという気がしている。

### 現状

```ruby
  t.string  "title",      null: false
  t.integer "event_id",   null: false
  t.string  "speaker_name",  null: false
  t.string  "speaker_email", null: false
  t.string  "speaker_sns_id"
  t.string  "speaker_sns_url"
  t.string  "speaker_belongs"
  t.string  "speaker_role"
  t.string  "slide_url"
  t.string  "video_url"
```

### 考えていること

- SNS 複数ほしい気がする
  - Twitter, GitHub, Facebook, Dribbble, Instagram, etc...
  - 設計どうするか悩むところ
- Secret URL 的なやつで登壇者がセルフサービスで修正できるようにしたい
  - `secret_token` みたいなカラムがあれば良さそう
- 公開情報と非公開情報をわかりやすくしておきたい
  - `speaker_email` とか公開しないと思うので、`secret_speaker_email` とか？（わからん）

**Comment by ukstudio** [comment]
とりあえずdescriptionがtalkにはないのでDBにカラムを追加しないとなって思ってる(表示するのであれば)

**Comment by ukstudio** [comment]
SNS複数はやるコスパがあわない気がするので、今のconnpassと同じでその人の活動が中心になっているアカウントなりURLなりを1つ教えてもらうのでいいとおもう。

**Comment by ukstudio** [comment]
ページは一応できたので一旦閉じる。
SNS複数にする件とかは個別に必要に応じてIssueにしよう。
